version: '3.8'

services:
  web:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - ${DOCKER_WEB_PORT}:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      #- ./docker/nginx/certs:/etc/nginx/certs
      - ./:/var/www/html
    links:
      - php

  php:
    image: php:8.1-fpm
    container_name: php
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: